version: "3"
services:

  #container for connecting to localhost
  dockerhost:
    container_name: dockerhost
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: always


  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - 80:80
      - 443:443
    restart: always